anchor_version = "0.27.0"

[workspace]
types = "packages/simple-admin-sdk/generated/"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
simple_admin = "sa3HiPEaDZk5JyU1CCmmRbcWnBc9U4TzHq42RWVUNQS"

[programs.devnet]
simple_admin = "sa3HiPEaDZk5JyU1CCmmRbcWnBc9U4TzHq42RWVUNQS"

[programs.localnet]
simple_admin = "sa3HiPEaDZk5JyU1CCmmRbcWnBc9U4TzHq42RWVUNQS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
