anchor_version = "0.28.0"

[workspace]
types = "packages/simple-admin-sdk/generated/"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
simple_admin = "sa4ihCaRZKuYZtY4fcdnNqx9vx9Lc6KELrL2nBkzNn2"

[programs.devnet]
simple_admin = "sa4ihCaRZKuYZtY4fcdnNqx9vx9Lc6KELrL2nBkzNn2"

[programs.localnet]
simple_admin = "sa4ihCaRZKuYZtY4fcdnNqx9vx9Lc6KELrL2nBkzNn2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
