[workspace]
types = "packages/simple-admin-sdk/generated/"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
simple_admin = "sa2LFTHaNfhHz2ES5oNFoGcLRC6E3cFr5KX4YGFANwv"

[programs.devnet]
simple_admin = "sa2LFTHaNfhHz2ES5oNFoGcLRC6E3cFr5KX4YGFANwv"

[programs.localnet]
simple_admin = "sa2LFTHaNfhHz2ES5oNFoGcLRC6E3cFr5KX4YGFANwv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
