name: Anchor Test

on:
  # push:
  #    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # from https://github.com/ochaloup/projectserum-build-docker
    container: docker.io/ochaloup/projectserum-build:v0.27.0_rust1.68-nightly_sol1.14.16_avm
    steps:
      - name: /root/.cargo to PATH
        run: |
          echo '/root/.cargo/bin/' >> $GITHUB_PATH
          echo '/root/.avm/bin' >> $GITHUB_PATH
          ln -s /root/.avm $HOME/
      - name: Info on AVM
        run: |
          avm list
          avm use 0.27.0
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set nightly toolchain
        run: rustup default nightly
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Generate new keygen
        run: |
          solana-keygen new --no-bip39-passphrase
          solana-keygen new --no-bip39-passphrase -o /root/.config/solana/id.json
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get

      - name: Running tests for project
        run: |
          pnpm install
          pnpm test
