name: Linting checks

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: pnpm install
      - run: pnpm lint
